const express=require("express");
const auth=require("../../common/middleware/auth");
const asyncHandler=require("../../common/utils/async-handler");
const {validateBody}=require("../../common/middleware/validate");
const controller=require("./system-knowledge-base.controller");
const {upload,knowledgeBaseSchema,incubationKnowledgeSyncSchema}=require("./system-knowledge-base.schema");
const router=express.Router();
router.use(auth);
router.get("/",asyncHandler(controller.listKnowledgeBases));
router.post("/",validateBody(knowledgeBaseSchema),asyncHandler(controller.createKnowledgeBase));
router.post("/documents/:documentId/reparse",asyncHandler(controller.reparseKnowledgeDocument));
router.get("/documents/:documentId/preview",asyncHandler(controller.previewKnowledgeDocument));
router.get("/documents/:documentId/download",asyncHandler(controller.downloadKnowledgeDocument));
router.delete("/documents/:documentId",asyncHandler(controller.deleteKnowledgeDocument));
router.post("/sync/incubation/:incubationId",validateBody(incubationKnowledgeSyncSchema),asyncHandler(controller.syncIncubationKnowledgeBase));
router.post("/:id/documents",upload.single("file"),asyncHandler(controller.uploadKnowledgeDocument));
router.get("/:id",asyncHandler(controller.getKnowledgeBaseDetail));
router.put("/:id",validateBody(knowledgeBaseSchema),asyncHandler(controller.updateKnowledgeBase));
router.delete("/:id",asyncHandler(controller.deleteKnowledgeBase));
module.exports=router;
