import type {UserProfile} from "../types/api";
export type ModulePermission="overview"|"ingestion"|"quality"|"processing"|"data_map"|"standards"|"services"|"reporting"|"data_modeling"|"system_services"|"system_users"|"system_roles"|"system_models"|"system_projects";
export const MODULE_ROUTE_PRIORITY=[{permission:"overview",path:"/dashboard/overview"},{permission:"ingestion",path:"/dashboard/data-sources"},{permission:"quality",path:"/dashboard/quality-control/data-sources"},{permission:"data_map",path:"/dashboard/data-map/resources"},{permission:"standards",path:"/dashboard/data-standards/overview"},{permission:"services",path:"/dashboard/services"},{permission:"reporting",path:"/dashboard/reporting/overview"},{permission:"data_modeling",path:"/dashboard/data-modeling/model-overview"},{permission:"system_services",path:"/dashboard/system-services"},{permission:"system_models",path:"/dashboard/system-models"},{permission:"system_projects",path:"/dashboard/system-projects"},{permission:"system_users",path:"/dashboard/system-users"},{permission:"system_roles",path:"/dashboard/system-roles"}] as Array<{permission:ModulePermission;path:string}>;
export function hasModulePermission(user:UserProfile|null,permission:ModulePermission){return (user?.permissions?.modules||[]).includes(permission);}
export function hasAnyModulePermission(user:UserProfile|null,permissions:ModulePermission[]){return permissions.some((permission)=>hasModulePermission(user,permission));}
export function getFirstAccessiblePath(user:UserProfile|null){return MODULE_ROUTE_PRIORITY.find((item)=>hasModulePermission(user,item.permission))?.path||"/dashboard/overview";}
export function getRequiredAnyPermissionsForPath(pathname:string):ModulePermission[]{return pathname.startsWith("/dashboard/asset-search")?["data_map","ingestion","quality","services"]:[];}
export function getRequiredPermissionForPath(pathname:string):ModulePermission|null{if(pathname.startsWith("/dashboard/asset-search"))return null;if(pathname.startsWith("/dashboard/data-modeling"))return "data_modeling";if(pathname.startsWith("/dashboard/data-standards"))return "standards";if(pathname.startsWith("/dashboard/data-map"))return "data_map";if(pathname.startsWith("/dashboard/reporting"))return "reporting";if(pathname.startsWith("/dashboard/data-development"))return "ingestion";if(pathname.startsWith("/dashboard/data-"))return "ingestion";if(pathname.startsWith("/dashboard/quality-control"))return "quality";if(pathname.startsWith("/dashboard/services")||pathname.startsWith("/dashboard/service-"))return "services";if(pathname.startsWith("/dashboard/system-users"))return "system_users";if(pathname.startsWith("/dashboard/system-roles"))return "system_roles";if(pathname.startsWith("/dashboard/system-models"))return "system_models";if(pathname.startsWith("/dashboard/system-projects"))return "system_projects";if(pathname.startsWith("/dashboard/system"))return "system_services";if(pathname.startsWith("/dashboard/overview"))return "overview";return null;}
export function getRequiredLicenseFeatureForPath(pathname:string){return getRequiredPermissionForPath(pathname);}
