const SOURCE_API_KEYS = Object.freeze([
  "GET /api/v1/data-map/overview", "GET /api/v1/data-map/departments", "POST /api/v1/data-map/departments", "PUT /api/v1/data-map/departments/:id", "DELETE /api/v1/data-map/departments/:id",
  "GET /api/v1/data-map/business-systems", "POST /api/v1/data-map/business-systems", "PUT /api/v1/data-map/business-systems/:id", "DELETE /api/v1/data-map/business-systems/:id",
  "GET /api/v1/data-map/data-sources/external", "GET /api/v1/data-map/data-sources", "POST /api/v1/data-map/data-sources", "PUT /api/v1/data-map/data-sources/:id", "DELETE /api/v1/data-map/data-sources/:id", "POST /api/v1/data-map/data-sources/test-connection", "GET /api/v1/data-map/data-sources/:id/tables", "GET /api/v1/data-map/data-sources/:id/tables/:tableName/columns",
  "GET /api/v1/data-map/catalogs/tree", "GET /api/v1/data-map/catalogs", "POST /api/v1/data-map/catalogs", "PUT /api/v1/data-map/catalogs/:id", "DELETE /api/v1/data-map/catalogs/:id", "POST /api/v1/data-map/catalogs/:id/register-resources",
  "POST /api/v1/data-map/lineage/refresh-ingestion", "GET /api/v1/data-map/ai-configs", "PUT /api/v1/data-map/ai-configs/:id", "GET /api/v1/data-map/search/resources", "GET /api/v1/data-map/resources", "POST /api/v1/data-map/resources/batch-delete", "GET /api/v1/data-map/resources/:id", "PUT /api/v1/data-map/resources/:id", "DELETE /api/v1/data-map/resources/:id", "PUT /api/v1/data-map/resources/:id/content", "PUT /api/v1/data-map/resources/:id/fields/:columnName", "GET /api/v1/data-map/resources/:id/profile", "POST /api/v1/data-map/resources/:id/profile/refresh", "POST /api/v1/data-map/resources/:id/profile/content-ai-analyze", "POST /api/v1/data-map/resources/:id/profile/fields-ai-analyze", "POST /api/v1/data-map/resources/:id/profile/ai-analyze", "GET /api/v1/data-map/resources/:id/lineage-graph", "GET /api/v1/data-map/resources/:id/sample",
]);
const PORTS = Object.freeze(["getOverview", "listDepartments", "createDepartment", "updateDepartment", "deleteDepartment", "listBusinessSystems", "createBusinessSystem", "updateBusinessSystem", "deleteBusinessSystem", "listExternalDataSources", "listDataSources", "createDataSource", "updateDataSource", "deleteDataSource", "testDataSource", "listDataSourceTables", "listDataSourceColumns", "listCatalogTree", "listCatalogs", "createCatalog", "updateCatalog", "deleteCatalog", "registerResources", "refreshIngestionLineage", "listAiConfigs", "updateAiConfig", "searchResources", "listResources", "deleteResources", "getResourceDetail", "updateResource", "deleteResource", "updateResourceContent", "updateResourceField", "getResourceProfile", "refreshResourceProfile", "analyzeResourceContentProfile", "analyzeResourceFieldProfile", "analyzeResourceProfile", "getResourceLineageGraph", "sampleResourceRows"]);
const SOURCE_FRONTEND_KEYS = Object.freeze(["/dashboard/data-map", "/dashboard/data-map/resources", "/dashboard/data-map/departments", "/dashboard/data-map/systems", "/dashboard/data-map/sources", "/dashboard/data-map/models"]);
const CAPABILITY_DEFINITIONS = Object.freeze(SOURCE_API_KEYS.map((sourceApiKey, index) => { const name = PORTS[index]; const api = name.startsWith("analyzeResource"); return Object.freeze({ capabilityId: `dataMap.${name}`, sourceApiKeys: Object.freeze([sourceApiKey]), sourceFrontendKeys: SOURCE_FRONTEND_KEYS, inputSchema: Object.freeze({ type: "object", additionalProperties: true }), outputSchema: Object.freeze({ type: "object" }), permission: Object.freeze({ allOf: Object.freeze(["data_map"]) }), mutation: Object.freeze({ kind: /^(create|update|delete|register|refresh|test|analyze)/.test(name) ? "write" : "read", idempotent: !/^(create|register|refresh|analyze)/.test(name) }), executionTargets: Object.freeze(api ? ["mysql", "api"] : ["mysql"]), port: name }); }));
module.exports = { SOURCE_API_KEYS, SOURCE_FRONTEND_KEYS, CAPABILITY_DEFINITIONS };
