const SOURCE_API_KEYS = Object.freeze(["GET /api/v1/data-services/overview","GET /api/v1/data-services/ops-dashboard","GET /api/v1/data-services/data-sources","POST /api/v1/data-services/data-sources","PUT /api/v1/data-services/data-sources/:id","DELETE /api/v1/data-services/data-sources/:id","POST /api/v1/data-services/data-sources/test-connection","GET /api/v1/data-services/data-sources/:id/tables","GET /api/v1/data-services/data-sources/:id/tables/:tableName/columns","GET /api/v1/data-services/data-sources/:id/tables/:tableName/sample","POST /api/v1/data-services/data-sources/sql-preview","GET /api/v1/data-services/services","POST /api/v1/data-services/services/recommend-config","POST /api/v1/data-services/services","PUT /api/v1/data-services/services/:id/status","PUT /api/v1/data-services/services/:id","DELETE /api/v1/data-services/services/:id","GET /api/v1/data-services/services/:id/docx","POST /api/v1/data-services/services/:id/debug","GET /api/v1/data-services/ai-configs","PUT /api/v1/data-services/ai-configs/:id","GET /api/v1/data-services/apps","POST /api/v1/data-services/apps","PUT /api/v1/data-services/apps/:id","DELETE /api/v1/data-services/apps/:id","GET /api/v1/data-services/authorizations","POST /api/v1/data-services/authorizations","PUT /api/v1/data-services/authorizations/:id","DELETE /api/v1/data-services/authorizations/:id","GET /api/v1/data-services/logs"]);
const PORTS = Object.freeze(["getOverview","getOpsDashboard","listServiceDataSources","createServiceDataSource","updateServiceDataSource","deleteServiceDataSource","testServiceDataSourceConnection","listServiceDataSourceTables","listServiceDataSourceColumns","sampleServiceDataSourceRows","previewServiceSql","listServices","recommendServiceConfig","createService","updateServiceStatus","updateService","deleteService","exportServiceInterfaceDoc","debugService","listServiceAiConfigs","updateServiceAiConfig","listServiceApps","createServiceApp","updateServiceApp","deleteServiceApp","listAuthorizations","createAuthorization","updateAuthorization","deleteAuthorization","listServiceLogs"]);
const SOURCE_FRONTEND_KEYS = Object.freeze([]);
const TARGETS = Object.freeze([["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql", "postgresql"], ["mysql", "postgresql"], ["mysql", "postgresql"], ["mysql", "postgresql"], ["mysql", "postgresql"], ["mysql"], ["mysql", "api"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql", "postgresql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"]]);
const METHODS = Object.freeze(["GET","GET","GET","POST","PUT","DELETE","POST","GET","GET","GET","POST","GET","POST","POST","PUT","PUT","DELETE","GET","POST","GET","PUT","GET","POST","PUT","DELETE","GET","POST","PUT","DELETE","GET"]);
const CAPABILITY_DEFINITIONS = Object.freeze(SOURCE_API_KEYS.map((sourceApiKey, index) => {
  const port = PORTS[index];
  const write = METHODS[index] !== "GET";
  return Object.freeze({ capabilityId: "dataServices." + port, sourceApiKeys: Object.freeze([sourceApiKey]), sourceFrontendKeys: SOURCE_FRONTEND_KEYS, inputSchema: Object.freeze({ type: "object", additionalProperties: true }), outputSchema: Object.freeze({ type: "object" }), permission: Object.freeze({ allOf: Object.freeze(["data_services"]) }), mutation: Object.freeze({ kind: write ? "write" : "read", idempotent: !write || /^(preview|test|suggest|run|query|analy)/i.test(port) }), executionTargets: Object.freeze(TARGETS[index]), port });
}));
module.exports = { SOURCE_API_KEYS, SOURCE_FRONTEND_KEYS, CAPABILITY_DEFINITIONS };
