const SOURCE_API_KEYS = Object.freeze(["GET /api/v1/reporting/runtime/dashboards/:id/theme-templates","POST /api/v1/reporting/runtime/dashboards/:id/preview-chart","GET /api/v1/reporting/overview","POST /api/v1/reporting/ai/chart/analysis-suggestions","POST /api/v1/reporting/ai/chart/sql-plan","POST /api/v1/reporting/ai/chart/sql-revise","POST /api/v1/reporting/ai/chart/query","POST /api/v1/reporting/ai/chart/recommend","POST /api/v1/reporting/ai/chart/field-map","GET /api/v1/reporting/data-sources","POST /api/v1/reporting/data-sources","PUT /api/v1/reporting/data-sources/:id","DELETE /api/v1/reporting/data-sources/:id","POST /api/v1/reporting/data-sources/test-connection","GET /api/v1/reporting/data-sources/:id/tables","GET /api/v1/reporting/data-sources/:id/tables/:tableName/columns","GET /api/v1/reporting/data-sources/:id/tables/:tableName/sample","GET /api/v1/reporting/dataset-folders","POST /api/v1/reporting/dataset-folders","PUT /api/v1/reporting/dataset-folders/:id","DELETE /api/v1/reporting/dataset-folders/:id","GET /api/v1/reporting/datasets","POST /api/v1/reporting/datasets/preview","POST /api/v1/reporting/datasets","PUT /api/v1/reporting/datasets/:id","DELETE /api/v1/reporting/datasets/:id","GET /api/v1/reporting/chart-assets","POST /api/v1/reporting/chart-assets","PUT /api/v1/reporting/chart-assets/:id","DELETE /api/v1/reporting/chart-assets/:id","GET /api/v1/reporting/theme-templates","POST /api/v1/reporting/theme-templates","PUT /api/v1/reporting/theme-templates/:id","DELETE /api/v1/reporting/theme-templates/:id","GET /api/v1/reporting/dashboards","GET /api/v1/reporting/dashboards/:id","POST /api/v1/reporting/dashboards/:id/publish","POST /api/v1/reporting/dashboards/preview-chart","POST /api/v1/reporting/dashboards","PUT /api/v1/reporting/dashboards/:id","DELETE /api/v1/reporting/dashboards/:id"]);
const PORTS = Object.freeze(["listRuntimeReportThemeTemplates","previewRuntimeDashboardChart","getOverview","suggestAiChartAnalysis","planAiChartSql","reviseAiChartSql","runAiChartQuery","recommendAiChart","allocateAiChartFieldMap","listReportDataSources","createReportDataSource","updateReportDataSource","deleteReportDataSource","testReportDataSourceConnection","listReportDataSourceTables","listReportDataSourceColumns","sampleReportDataSourceRows","listReportDatasetFolders","createReportDatasetFolder","updateReportDatasetFolder","deleteReportDatasetFolder","listReportDatasets","previewReportDataset","createReportDataset","updateReportDataset","deleteReportDataset","listReportChartAssets","createReportChartAsset","updateReportChartAsset","deleteReportChartAsset","listReportThemeTemplates","createReportThemeTemplate","updateReportThemeTemplate","deleteReportThemeTemplate","listReportDashboards","getReportDashboard","publishReportDashboard","previewDashboardChart","createReportDashboard","updateReportDashboard","deleteReportDashboard"]);
const SOURCE_FRONTEND_KEYS = Object.freeze(["/dashboard/reporting/overview","/dashboard/reporting/data-sources","/dashboard/reporting/datasets","/dashboard/reporting/workbench","/dashboard/reporting/chart-library","/dashboard/reporting/theme-templates","/dashboard/reporting/models","/dashboard/reporting"]);
const TARGETS = Object.freeze([["mysql"], ["mysql", "postgresql", "oracle", "dm"], ["mysql"], ["mysql", "api"], ["mysql", "api"], ["mysql", "api"], ["mysql", "postgresql", "oracle", "dm", "api"], ["mysql", "api"], ["mysql", "api"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"], ["mysql"]]);
const METHODS = Object.freeze(["GET","POST","GET","POST","POST","POST","POST","POST","POST","GET","POST","PUT","DELETE","POST","GET","GET","GET","GET","POST","PUT","DELETE","GET","POST","POST","PUT","DELETE","GET","POST","PUT","DELETE","GET","POST","PUT","DELETE","GET","GET","POST","POST","POST","PUT","DELETE"]);
const CAPABILITY_DEFINITIONS = Object.freeze(SOURCE_API_KEYS.map((sourceApiKey, index) => {
  const port = PORTS[index];
  const write = METHODS[index] !== "GET";
  return Object.freeze({ capabilityId: "reporting." + port, sourceApiKeys: Object.freeze([sourceApiKey]), sourceFrontendKeys: SOURCE_FRONTEND_KEYS, inputSchema: Object.freeze({ type: "object", additionalProperties: true }), outputSchema: Object.freeze({ type: "object" }), permission: Object.freeze({ allOf: Object.freeze(["reporting"]) }), mutation: Object.freeze({ kind: write ? "write" : "read", idempotent: !write || /^(preview|test|suggest|run|query|analy)/i.test(port) }), executionTargets: Object.freeze(TARGETS[index]), port });
}));
module.exports = { SOURCE_API_KEYS, SOURCE_FRONTEND_KEYS, CAPABILITY_DEFINITIONS };
