export const medataFoundations = {
  colors: {
    primary: "#1677ff",
    primaryHover: "#4096ff",
    primaryActive: "#0958d9",
    primarySoft: "#eaf3ff",
    primarySoftHover: "#d8e9ff",
    canvas: "#f5f7fa",
    surface: "#ffffff",
    surfaceSubtle: "#f8fafc",
    surfaceHover: "#f3f6fa",
    border: "#e5e9f0",
    borderStrong: "#d4dae4",
    text: "#1f2329",
    textSecondary: "#667085",
    textTertiary: "#98a2b3",
    disabled: "#c0c7d1",
    success: "#16a34a",
    successSoft: "#f0fdf4",
    warning: "#d97706",
    warningSoft: "#fffbeb",
    error: "#dc2626",
    errorSoft: "#fef2f2",
    info: "#1677ff",
    infoSoft: "#eaf3ff",
    neutralSoft: "#f2f4f7",
  },
  typography: {
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif',
    fontSizeXs: 12,
    fontSizeSm: 13,
    fontSizeBase: 14,
    fontSizeLg: 16,
    fontSizeXl: 20,
    fontSize2xl: 24,
    fontSizeDisplay: 28,
  },
  spacing: {
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
    8: 32,
    10: 40,
  },
  radii: {
    xs: 4,
    sm: 6,
    md: 8,
    lg: 10,
    xl: 12,
    pill: 999,
  },
  shadows: {
    none: "none",
    float: "0 8px 24px rgba(15, 23, 42, 0.10)",
    modal: "0 24px 56px rgba(15, 23, 42, 0.16)",
  },
  motion: {
    fast: "120ms ease-out",
    base: "180ms ease-out",
    panel: "240ms ease-out",
  },
  layout: {
    headerHeight: 56,
    siderWidth: 176,
    contentMaxWidth: "none",
  },
  controls: {
    compactHeight: 32,
    defaultHeight: 36,
    prominentHeight: 40,
  },
} as const;

const px = (value: number) => `${value}px`;

export const medataCssVariables = {
  "--md-color-primary": medataFoundations.colors.primary,
  "--md-color-primary-hover": medataFoundations.colors.primaryHover,
  "--md-color-primary-active": medataFoundations.colors.primaryActive,
  "--md-color-primary-soft": medataFoundations.colors.primarySoft,
  "--md-color-primary-soft-hover": medataFoundations.colors.primarySoftHover,
  "--md-color-canvas": medataFoundations.colors.canvas,
  "--md-color-surface": medataFoundations.colors.surface,
  "--md-color-surface-subtle": medataFoundations.colors.surfaceSubtle,
  "--md-color-surface-hover": medataFoundations.colors.surfaceHover,
  "--md-color-border": medataFoundations.colors.border,
  "--md-color-border-strong": medataFoundations.colors.borderStrong,
  "--md-color-text": medataFoundations.colors.text,
  "--md-color-text-secondary": medataFoundations.colors.textSecondary,
  "--md-color-text-tertiary": medataFoundations.colors.textTertiary,
  "--md-color-disabled": medataFoundations.colors.disabled,
  "--md-color-success": medataFoundations.colors.success,
  "--md-color-success-soft": medataFoundations.colors.successSoft,
  "--md-color-warning": medataFoundations.colors.warning,
  "--md-color-warning-soft": medataFoundations.colors.warningSoft,
  "--md-color-error": medataFoundations.colors.error,
  "--md-color-error-soft": medataFoundations.colors.errorSoft,
  "--md-color-info": medataFoundations.colors.info,
  "--md-color-info-soft": medataFoundations.colors.infoSoft,
  "--md-color-neutral-soft": medataFoundations.colors.neutralSoft,
  "--md-font-family": medataFoundations.typography.fontFamily,
  "--md-font-size-xs": px(medataFoundations.typography.fontSizeXs),
  "--md-font-size-sm": px(medataFoundations.typography.fontSizeSm),
  "--md-font-size-base": px(medataFoundations.typography.fontSizeBase),
  "--md-font-size-lg": px(medataFoundations.typography.fontSizeLg),
  "--md-font-size-xl": px(medataFoundations.typography.fontSizeXl),
  "--md-font-size-2xl": px(medataFoundations.typography.fontSize2xl),
  "--md-font-size-display": px(medataFoundations.typography.fontSizeDisplay),
  "--md-space-1": px(medataFoundations.spacing[1]),
  "--md-space-2": px(medataFoundations.spacing[2]),
  "--md-space-3": px(medataFoundations.spacing[3]),
  "--md-space-4": px(medataFoundations.spacing[4]),
  "--md-space-5": px(medataFoundations.spacing[5]),
  "--md-space-6": px(medataFoundations.spacing[6]),
  "--md-space-8": px(medataFoundations.spacing[8]),
  "--md-space-10": px(medataFoundations.spacing[10]),
  "--md-radius-xs": px(medataFoundations.radii.xs),
  "--md-radius-sm": px(medataFoundations.radii.sm),
  "--md-radius-md": px(medataFoundations.radii.md),
  "--md-radius-lg": px(medataFoundations.radii.lg),
  "--md-radius-xl": px(medataFoundations.radii.xl),
  "--md-radius-pill": px(medataFoundations.radii.pill),
  "--md-shadow-none": medataFoundations.shadows.none,
  "--md-shadow-float": medataFoundations.shadows.float,
  "--md-shadow-modal": medataFoundations.shadows.modal,
  "--md-motion-fast": medataFoundations.motion.fast,
  "--md-motion-base": medataFoundations.motion.base,
  "--md-motion-panel": medataFoundations.motion.panel,
  "--md-header-height": px(medataFoundations.layout.headerHeight),
  "--md-sider-width": px(medataFoundations.layout.siderWidth),
  "--md-content-max-width": medataFoundations.layout.contentMaxWidth,
  "--md-control-height-compact": px(medataFoundations.controls.compactHeight),
  "--md-control-height": px(medataFoundations.controls.defaultHeight),
  "--md-control-height-prominent": px(medataFoundations.controls.prominentHeight),
} satisfies Record<`--${string}`, string>;

export function applyMedataCssVariables(root: HTMLElement = document.documentElement) {
  Object.entries(medataCssVariables).forEach(([name, value]) => {
    root.style.setProperty(name, value);
  });
}
