const SOURCE_API_KEYS = Object.freeze([
  "POST /api/v1/asset-search/search",
  "POST /api/v1/asset-search/business-data/search",
  "GET /api/v1/asset-search/suggest",
  "GET /api/v1/asset-search/facets",
  "GET /api/v1/asset-search/ai-configs",
  "PUT /api/v1/asset-search/ai-configs/:id",
  "GET /api/v1/asset-search/ai-runs",
  "POST /api/v1/asset-search/feedback",
]);

const SOURCE_FRONTEND_KEYS = Object.freeze([
  "frontend/src/pages/asset-search/AssetSearchPage.tsx",
  "frontend/src/pages/asset-search/BusinessDataSearchPage.tsx",
  "frontend/src/pages/asset-search/AssetSearchModelManagementPage.tsx",
]);

const ASSET_TYPES = Object.freeze([
  "table",
  "field",
  "datasource",
  "ingestion_task",
  "quality_rule",
  "quality_strategy",
  "quality_result",
  "service_api",
  "service_app",
]);

const SOURCE_MODULES = Object.freeze(["data_map", "ingestion", "quality", "services"]);

const CAPABILITY_DEFINITIONS = Object.freeze([
  {
    id: "assetSearch.search",
    capabilityId: "assetSearch.search",
    sourceApiKeys: Object.freeze([SOURCE_API_KEYS[0]]),
    sourceFrontendKeys: Object.freeze([SOURCE_FRONTEND_KEYS[0]]),
    inputSchema: Object.freeze({ type: "object", properties: { keyword: { type: "string" } } }),
    outputSchema: Object.freeze({ type: "object" }),
    permission: Object.freeze({ anyOf: Object.freeze(["data_map", "ingestion", "quality", "services"]) }),
    mutation: Object.freeze({ kind: "read", idempotent: true }),
    executionTargets: Object.freeze(["mysql"]),
    port: "search",
  },
  {
    id: "assetSearch.businessDataSearch",
    capabilityId: "assetSearch.businessDataSearch",
    sourceApiKeys: Object.freeze([SOURCE_API_KEYS[1]]),
    sourceFrontendKeys: Object.freeze([SOURCE_FRONTEND_KEYS[1]]),
    inputSchema: Object.freeze({ type: "object", required: ["conditions"] }),
    outputSchema: Object.freeze({ type: "object" }),
    permission: Object.freeze({ allOf: Object.freeze(["data_map"]) }),
    mutation: Object.freeze({ kind: "read", idempotent: true }),
    executionTargets: Object.freeze(["mysql", "managed-jdbc"]),
    port: "businessDataSearch",
  },
  {
    id: "assetSearch.suggest",
    capabilityId: "assetSearch.suggest",
    sourceApiKeys: Object.freeze([SOURCE_API_KEYS[2]]),
    sourceFrontendKeys: Object.freeze([SOURCE_FRONTEND_KEYS[0], SOURCE_FRONTEND_KEYS[1]]),
    inputSchema: Object.freeze({ type: "object" }),
    outputSchema: Object.freeze({ type: "array" }),
    permission: Object.freeze({ anyOf: Object.freeze(["data_map", "ingestion", "quality", "services"]) }),
    mutation: Object.freeze({ kind: "read", idempotent: true }),
    executionTargets: Object.freeze(["mysql"]),
    port: "suggest",
  },
  {
    id: "assetSearch.facets",
    capabilityId: "assetSearch.facets",
    sourceApiKeys: Object.freeze([SOURCE_API_KEYS[3]]),
    sourceFrontendKeys: Object.freeze([SOURCE_FRONTEND_KEYS[0], SOURCE_FRONTEND_KEYS[1]]),
    inputSchema: Object.freeze({ type: "object" }),
    outputSchema: Object.freeze({ type: "object" }),
    permission: Object.freeze({ anyOf: Object.freeze(["data_map", "ingestion", "quality", "services"]) }),
    mutation: Object.freeze({ kind: "read", idempotent: true }),
    executionTargets: Object.freeze(["mysql"]),
    port: "facets",
  },
  {
    id: "assetSearch.listAiConfigs",
    capabilityId: "assetSearch.listAiConfigs",
    sourceApiKeys: Object.freeze([SOURCE_API_KEYS[4]]),
    sourceFrontendKeys: Object.freeze([SOURCE_FRONTEND_KEYS[2]]),
    inputSchema: Object.freeze({ type: "object" }),
    outputSchema: Object.freeze({ type: "array" }),
    permission: Object.freeze({ anyOf: Object.freeze(["system_models", "data_map", "ingestion", "quality", "services"]) }),
    mutation: Object.freeze({ kind: "read", idempotent: true }),
    executionTargets: Object.freeze(["mysql"]),
    port: "listAiConfigs",
  },
  {
    id: "assetSearch.updateAiConfig",
    capabilityId: "assetSearch.updateAiConfig",
    sourceApiKeys: Object.freeze([SOURCE_API_KEYS[5]]),
    sourceFrontendKeys: Object.freeze([SOURCE_FRONTEND_KEYS[2]]),
    inputSchema: Object.freeze({ type: "object", required: ["id"] }),
    outputSchema: Object.freeze({ type: "object" }),
    permission: Object.freeze({ allOf: Object.freeze(["system_models"]) }),
    mutation: Object.freeze({ kind: "write", idempotent: true, audited: true }),
    executionTargets: Object.freeze(["mysql"]),
    port: "updateAiConfig",
  },
  {
    id: "assetSearch.listAiRuns",
    capabilityId: "assetSearch.listAiRuns",
    sourceApiKeys: Object.freeze([SOURCE_API_KEYS[6]]),
    sourceFrontendKeys: Object.freeze([SOURCE_FRONTEND_KEYS[2]]),
    inputSchema: Object.freeze({ type: "object" }),
    outputSchema: Object.freeze({ type: "array" }),
    permission: Object.freeze({ anyOf: Object.freeze(["system_models", "system_roles", "system_users"]) }),
    mutation: Object.freeze({ kind: "read", idempotent: true }),
    executionTargets: Object.freeze(["mysql"]),
    port: "listAiRuns",
  },
  {
    id: "assetSearch.feedback",
    capabilityId: "assetSearch.feedback",
    sourceApiKeys: Object.freeze([SOURCE_API_KEYS[7]]),
    sourceFrontendKeys: Object.freeze([SOURCE_FRONTEND_KEYS[0]]),
    inputSchema: Object.freeze({ type: "object", required: ["resultId", "feedback"] }),
    outputSchema: Object.freeze({ type: "object" }),
    permission: Object.freeze({ anyOf: Object.freeze(["data_map", "ingestion", "quality", "services"]) }),
    mutation: Object.freeze({ kind: "write", idempotent: false, audited: true }),
    executionTargets: Object.freeze(["mysql"]),
    port: "feedback",
  },
]);

module.exports = {
  ASSET_TYPES,
  CAPABILITY_DEFINITIONS,
  SOURCE_API_KEYS,
  SOURCE_FRONTEND_KEYS,
  SOURCE_MODULES,
};
